### ISSUE TITLE
Can not build!

### ISSUE THREAD

**Issue by thatcatdrout** [aboutDavid/personal-website#1]
When i try to build with `yarn start` i get this:

~/personal-website $ yarn start                         yarn run v1.22.10                                       $ eleventy                                              > res.filter is not a function                                                                                  `TypeError` was thrown:
    TypeError: res.filter is not a function
        at Object.<anonymous> (/data/data/com.termux/files/home/personal-website/_data/posts.js:22:11)
        at Module._compile (internal/modules/cjs/loader.js:1063:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
        at Module.load (internal/modules/cjs/loader.js:928:32)                                                          at Function.Module._load (internal/modules/cjs/loader.js:769:14)
        at Module.require (internal/modules/cjs/loader.js:952:19)
        at require (internal/modules/cjs/helpers.js:88:18)
        at TemplateData.getDataValue (/data/data/com.termux/files/home/personal-website/node_modules/@11ty/eleventy/src/TemplateData.js:383:25)
        at async TemplateData.getAllGlobalData (/data/data/com.termux/files/home/personal-website/node_modules/@11ty/eleventy/src/TemplateData.js:228:18)
        at async TemplateData.getData (/data/data/com.termux/files/home/personal-website/node_modules/@11ty/eleventy/src/TemplateData.js:255:24)                        error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Help!

**Comment by aboutDavid** [comment]
Because you didn't give any API keys, I'm not giving help on how to build it (you can see there is no readme or any .env tokens)
